export const EYE_COLORS = [
  'Blue',
  'Brown',
  'Green',
  'Hazel',
  'Gray',
  'Amber',
  'Green-Blue',
  'Brown-Black'
];

export const HAIR_COLORS = [
  'Black',
  'Brown',
  'Blonde',
  'Red',
  'Gray',
  'White',
  'Auburn',
  'Chestnut',
  'Golden',
  'Platinum'
];

export const HAIR_STYLES = [
  'Short',
  'Medium',
  'Long',
  'Curly',
  'Straight',
  'Wavy',
  'Bald',
  'Shaved',
  'Ponytail',
  'Braids',
  'Dreadlocks',
  'Spiky'
];

export const ETHNICITIES = [
  'Caucasian',
  'Black/African',
  'Asian',
  'Hispanic/Latino',
  'Middle Eastern',
  'Native American',
  'Pacific Islander',
  'Mixed',
  'Indian',
  'Mediterranean'
];

export const RELIGIONS = [
  'Christianity',
  'Catholic',
  'Protestant',
  'Islam',
  'Judaism',
  'Buddhism',
  'Hinduism',
  'Atheist',
  'Agnostic',
  'Spiritual'
];

export const EDUCATION_LEVELS = [
  'High School',
  'Some College',
  'Associate Degree',
  'Bachelor\'s Degree',
  'Master\'s Degree',
  'PhD/Doctorate',
  'Trade School',
  'Self-taught'
];

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Russian',
  'Chinese',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Turkish',
  'Dutch',
  'Swedish'
];

export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
  'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada',
  'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia',
  'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
  'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia',
  'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
  'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
  'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
  'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
  'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia',
  'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
  'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea',
  'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis',
  'Saint Lucia', 'Saint Vincent', 'Samoa', 'San Marino', 'Sao Tome', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
  'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
  'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
  'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
  'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
  'Zimbabwe'
];

export const MAJOR_CITIES  = {
  'Afghanistan': ['Kabul','Herat','Kandahar','Mazar-i-Sharif','Jalalabad','Kunduz','Taloqan','Pul-i-Khumri','Ghazni','Khost','Bamyan','Farah','Lashkar Gah','Maymana','Sheberghan'],
  'Albania': ['Tirana','Durrës','Vlorë','Shkodër','Fier','Elbasan','Korçë','Berat','Lushnjë','Pogradec','Gjirokastër','Sarandë','Kukës','Lezhë','Peshkopi'],
  'Algeria': ['Algiers','Oran','Constantine','Annaba','Blida','Batna','Djelfa','Sétif','Sidi Bel Abbès','Skikda','Tébessa','Tlemcen','Bejaia','Mostaganem','Biskra','Ouargla','Ghardaïa'],
  'Andorra': ['Andorra la Vella','Escaldes-Engordany','Encamp','La Massana','Ordino','Canillo','Sant Julià de Lòria','Santa Coloma'],
  'Angola': ['Luanda','Huambo','Lobito','Benguela','Lubango','Malanje','Namibe','Soyo','Uíge','Kuito','Menongue','Ndalatando','Sumbe','Luena'],
  'Argentina': ['Buenos Aires','Córdoba','Rosario','Mendoza','La Plata','Mar del Plata','Salta','Santa Fe','San Juan','Neuquén','Tucumán','Bahía Blanca','San Luis','Río Cuarto','Comodoro Rivadavia','Ushuaia'],
  'Armenia': ['Yerevan','Gyumri','Vanadzor','Vagharshapat','Abovyan','Kapan','Hrazdan','Ararat','Armavir','Artashat','Ijevan','Gavar','Sevan','Ashtarak'],
  'Australia': ['Sydney','Melbourne','Brisbane','Perth','Adelaide','Canberra','Hobart','Darwin','Gold Coast','Newcastle','Wollongong','Geelong','Townsville','Cairns','Toowoomba','Ballarat'],
  'Austria': ['Vienna','Graz','Linz','Salzburg','Innsbruck','Klagenfurt','Villach','Wels','Sankt Pölten','Dornbirn','Bregenz','Feldkirch','Leoben','Krems'],
  'Azerbaijan': ['Baku','Ganja','Sumqayit','Mingachevir','Shirvan','Nakhchivan','Lankaran','Sheki','Yevlakh','Khirdalan','Shamakhi','Quba','Zaqatala','Agdam'],
  'Bahamas': ['Nassau','Freeport','West End','Marsh Harbour','George Town','Alice Town','Cooper’s Town','Andros Town'],
'Bahrain': ['Manama','Riffa','Muharraq','Hamad Town','Isa Town','Sitra','Budaiya','Zallaq'],
'Bangladesh': ['Dhaka','Chittagong','Khulna','Rajshahi','Sylhet','Barisal','Rangpur','Comilla','Narayanganj','Gazipur','Mymensingh','Jessore','Bogra'],
'Barbados': ['Bridgetown','Speightstown','Oistins','Holetown','Crane','Bathsheba','Six Roads'],
'Belarus': ['Minsk','Gomel','Mogilev','Vitebsk','Grodno','Brest','Bobruisk','Baranovichi','Borisov','Pinsk','Orsha'],
'Belgium': ['Brussels','Antwerp','Ghent','Charleroi','Liège','Bruges','Namur','Leuven','Mons','Mechelen','Aalst','Kortrijk'],
'Belize': ['Belize City','San Ignacio','Orange Walk','Corozal','Dangriga','Punta Gorda','Belmopan'],
'Benin': ['Cotonou','Porto-Novo','Parakou','Abomey','Bohicon','Djougou','Natitingou','Lokossa'],
'Bhutan': ['Thimphu','Phuntsholing','Paro','Punakha','Wangdue Phodrang','Gelephu','Samdrup Jongkhar'],
'Bolivia': ['La Paz','Santa Cruz de la Sierra','Cochabamba','Sucre','Oruro','Potosí','Tarija','Trinidad','El Alto','Cobija'],
'Bosnia and Herzegovina': ['Sarajevo','Banja Luka','Mostar','Zenica','Tuzla','Bijeljina','Prijedor','Brčko','Doboj'],
'Botswana': ['Gaborone','Francistown','Maun','Serowe','Selebi-Phikwe','Kanye','Molepolole','Jwaneng'],
'Brazil': ['São Paulo','Rio de Janeiro','Belo Horizonte','Brasília','Salvador','Fortaleza','Recife','Porto Alegre','Curitiba','Manaus','Belém','Goiânia','Campinas'],
'Brunei': ['Bandar Seri Begawan','Kuala Belait','Seria','Tutong','Bangar'],
'Bulgaria': ['Sofia','Plovdiv','Varna','Burgas','Ruse','Stara Zagora','Pleven','Sliven','Dobrich','Shumen','Haskovo'],
'Burkina Faso': ['Ouagadougou','Bobo-Dioulasso','Koudougou','Banfora','Ouahigouya','Tenkodogo','Dori'],
'Burundi': ['Gitega','Bujumbura','Muyinga','Ngozi','Ruyigi','Rumonge','Bururi'],
'Cambodia': ['Phnom Penh','Siem Reap','Battambang','Sihanoukville','Poipet','Kampong Cham','Takeo','Kampot','Kep','Pursat'],
'Cameroon': ['Douala','Yaoundé','Bamenda','Bafoussam','Garoua','Maroua','Ngaoundéré','Limbé','Buea','Kribi'],
'Canada': ['Toronto','Montreal','Vancouver','Calgary','Edmonton','Ottawa','Winnipeg','Hamilton','Kitchener','Waterloo','Mississauga','Brampton','Markham'],
'Cape Verde': ['Praia','Mindelo','Santa Maria','Assomada','São Filipe','Tarrafal'],
'Central African Republic': ['Bangui','Bimbo','Berbérati','Bossangoa','Bouar','Bria','Bangassou'],
'Chad': ['N’Djamena','Moundou','Sarh','Abéché','Kélo','Doba','Am Timan'],
'Chile': ['Santiago','Valparaíso','Concepción','La Serena','Antofagasta','Temuco','Rancagua','Talca','Iquique','Puerto Montt','Arica','Punta Arenas'],
'China': ['Beijing','Shanghai','Shenzhen','Guangzhou','Chengdu','Wuhan','Hangzhou','Nanjing','Xi’an','Chongqing','Tianjin','Suzhou','Qingdao'],
'Colombia': ['Bogotá','Medellín','Cali','Barranquilla','Cartagena','Bucaramanga','Cúcuta','Pereira','Manizales','Armenia','Ibagué','Villavicencio'],
'Comoros': ['Moroni','Mutsamudu','Fomboni','Domoni'],
'Congo': ['Brazzaville','Pointe-Noire','Dolisie','Nkayi','Ouesso','Impfondo'],
'Costa Rica': ['San José','Alajuela','Heredia','Cartago','Limón','Puntarenas','Liberia','Nicoya'],
'Croatia': ['Zagreb','Split','Rijeka','Osijek','Zadar','Pula','Šibenik','Dubrovnik','Karlovac','Sisak'],
'Cuba': ['Havana','Santiago de Cuba','Camagüey','Holguín','Santa Clara','Guantánamo','Cienfuegos','Matanzas'],
'Cyprus': ['Nicosia','Limassol','Larnaca','Famagusta','Paphos','Kyrenia'],
'Czech Republic': ['Prague','Brno','Ostrava','Plzeň','Liberec','Olomouc','Hradec Králové','Pardubice','Zlín'],
'Denmark': ['Copenhagen','Aarhus','Odense','Aalborg','Esbjerg','Randers','Kolding','Horsens','Vejle','Roskilde','Herning'],
'Djibouti': ['Djibouti City','Ali Sabieh','Tadjoura','Obock','Dikhil','Arta'],
'Dominica': ['Roseau','Portsmouth','Marigot','Castle Bruce','Saint Joseph'],
'Dominican Republic': ['Santo Domingo','Santiago de los Caballeros','La Romana','San Pedro de Macorís','San Cristóbal','Puerto Plata','La Vega','Bonao','Higüey'],
'Ecuador': ['Quito','Guayaquil','Cuenca','Santo Domingo','Machala','Manta','Portoviejo','Ambato','Loja','Ibarra'],
'Egypt': ['Cairo','Alexandria','Giza','Shubra El Kheima','Port Said','Suez','Mansoura','Tanta','Asyut','Ismailia','Faiyum','Zagazig','Luxor','Aswan'],
'El Salvador': ['San Salvador','Santa Ana','San Miguel','Soyapango','Santa Tecla','Apopa','Delgado','Ahuachapán'],
'Equatorial Guinea': ['Malabo','Bata','Ebebiyin','Aconibe','Mongomo','Evinayong'],
'Eritrea': ['Asmara','Keren','Massawa','Assab','Mendefera','Barentu'],
'Estonia': ['Tallinn','Tartu','Narva','Pärnu','Kohtla-Järve','Viljandi','Rakvere','Sillamäe'],
'Ethiopia': ['Addis Ababa','Dire Dawa','Mekelle','Gondar','Hawassa','Adama','Bahir Dar','Jimma','Dessie','Shashamane'],
'Fiji': ['Suva','Lautoka','Nadi','Labasa','Ba','Sigatoka'],
'Finland': ['Helsinki','Espoo','Tampere','Vantaa','Oulu','Turku','Jyväskylä','Kuopio','Lahti','Pori'],
'France': ['Paris','Marseille','Lyon','Toulouse','Nice','Nantes','Montpellier','Strasbourg','Bordeaux','Lille','Rennes','Reims','Le Havre','Saint-Étienne'],
'Gabon': ['Libreville','Port-Gentil','Franceville','Oyem','Moanda','Lambaréné'],
'Gambia': ['Banjul','Serekunda','Brikama','Bakau','Farafenni','Lamin'],
'Georgia': ['Tbilisi','Batumi','Kutaisi','Rustavi','Zugdidi','Gori','Poti','Kobuleti'],
'Germany': ['Berlin','Hamburg','Munich','Cologne','Frankfurt','Stuttgart','Düsseldorf','Dortmund','Essen','Leipzig','Bremen','Dresden','Hanover','Nuremberg'],
'Ghana': ['Accra','Kumasi','Tamale','Takoradi','Cape Coast','Koforidua','Sunyani','Ho','Wa'],
'Greece': ['Athens','Thessaloniki','Patras','Heraklion','Larissa','Volos','Rhodes','Chania','Rethymno','Ioannina'],
'Haiti': ['Port-au-Prince','Cap-Haïtien','Gonaïves','Les Cayes','Jacmel','Jérémie','Hinche'],
'Honduras': ['Tegucigalpa','San Pedro Sula','Choloma','La Ceiba','El Progreso','Comayagua','Danlí','Puerto Cortés'],
'Hungary': ['Budapest','Debrecen','Szeged','Miskolc','Pécs','Győr','Nyíregyháza','Kecskemét','Székesfehérvár','Szombathely'],
'Iceland': ['Reykjavík','Kópavogur','Hafnarfjörður','Akureyri','Reykjanesbær','Garðabær','Mosfellsbær','Akranes'],
'India': ['Mumbai','Delhi','Bengaluru','Chennai','Hyderabad','Kolkata','Pune','Ahmedabad','Jaipur','Chandigarh','Lucknow','Kanpur','Indore','Bhopal','Patna'],
'Indonesia': ['Jakarta','Surabaya','Bandung','Medan','Bekasi','Depok','Tangerang','Semarang','Palembang','Makassar','Batam','Bogor'],
'Iran': ['Tehran','Mashhad','Isfahan','Karaj','Tabriz','Shiraz','Qom','Ahvaz','Kermanshah','Urmia','Rasht'],
'Iraq': ['Baghdad','Basra','Mosul','Erbil','Sulaymaniyah','Kirkuk','Najaf','Karbala','Hillah','Duhok'],
'Ireland': ['Dublin','Cork','Limerick','Galway','Waterford','Drogheda','Dundalk','Swords'],
'Israel': ['Jerusalem','Tel Aviv','Haifa','Rishon LeZion','Petah Tikva','Ashdod','Netanya','Beer Sheva','Holon','Bnei Brak'],
'Italy': ['Rome','Milan','Naples','Turin','Palermo','Genoa','Bologna','Florence','Bari','Catania','Venice','Verona','Padua'],
'Jamaica': ['Kingston','Montego Bay','Spanish Town','Portmore','Mandeville','May Pen','Ocho Rios'],
'Japan': ['Tokyo','Yokohama','Osaka','Nagoya','Sapporo','Fukuoka','Kobe','Kyoto','Kawasaki','Saitama','Hiroshima','Sendai'],
'Jordan': ['Amman','Zarqa','Irbid','Aqaba','Salt','Madaba','Karak','Mafraq'],
'Kazakhstan': ['Almaty','Astana','Shymkent','Karaganda','Aktobe','Taraz','Pavlodar','Ust-Kamenogorsk','Semey','Atyrau','Kostanay'],
'Kenya': ['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Thika','Nyeri','Machakos','Meru','Malindi'],
'Kiribati': ['South Tarawa','Betio','Bikenibeu','Teaoraereke','Bairiki','Buota'],
'Kuwait': ['Kuwait City','Al Ahmadi','Hawalli','Salmiya','Farwaniya','Jahra','Mangaf'],
'Kyrgyzstan': ['Bishkek','Osh','Jalal-Abad','Karakol','Tokmok','Naryn','Talas'],
'Laos': ['Vientiane','Luang Prabang','Pakse','Savannakhet','Thakhek','Xam Neua','Muang Phonsavan'],
'Latvia': ['Riga','Daugavpils','Liepāja','Jelgava','Jūrmala','Ventspils','Rēzekne','Ogre'],
'Lebanon': ['Beirut','Tripoli','Sidon','Tyre','Zahle','Jounieh','Byblos','Baalbek'],
'Lesotho': ['Maseru','Teyateyaneng','Mafeteng','Hlotse','Mohale’s Hoek','Qacha’s Nek'],
'Liberia': ['Monrovia','Gbarnga','Buchanan','Kakata','Voinjama','Zwedru'],
'Libya': ['Tripoli','Benghazi','Misrata','Zawiya','Zliten','Sirte','Tobruk','Derna','Sabha'],
'Liechtenstein': ['Vaduz','Schaan','Balzers','Triesen','Eschen','Mauren'],
'Lithuania': ['Vilnius','Kaunas','Klaipėda','Šiauliai','Panevėžys','Alytus','Marijampolė','Mažeikiai'],
'Luxembourg': ['Luxembourg City','Esch-sur-Alzette','Differdange','Dudelange','Ettelbruck','Diekirch'],
'Madagascar': ['Antananarivo','Toamasina','Antsirabe','Fianarantsoa','Mahajanga','Toliara','Antsiranana','Ambatondrazaka'],
'Malawi': ['Lilongwe','Blantyre','Mzuzu','Zomba','Kasungu','Mangochi'],
'Malaysia': ['Kuala Lumpur','George Town','Johor Bahru','Shah Alam','Petaling Jaya','Ipoh','Kuching','Kota Kinabalu','Miri','Seremban'],
'Maldives': ['Malé','Hulhumalé','Addu City','Fuvahmulah','Kulhudhuffushi','Thinadhoo'],
'Mali': ['Bamako','Sikasso','Mopti','Kayes','Segou','Koutiala','Timbuktu','Gao'],
'Malta': ['Valletta','Birkirkara','Mosta','Qormi','Sliema','St. Julian’s','Paola'],
'Marshall Islands': ['Majuro','Ebeye','Arno','Wotje','Jaluit'],
'Mauritania': ['Nouakchott','Nouadhibou','Rosso','Kaédi','Zouerate','Atar'],
'Mauritius': ['Port Louis','Beau Bassin-Rose Hill','Vacoas-Phoenix','Curepipe','Quatre Bornes','Mahebourg'],
'Mexico': ['Mexico City','Guadalajara','Monterrey','Puebla','Tijuana','León','Ciudad Juárez','Mérida','Cancún','Querétaro','Toluca','Aguascalientes'],
'Namibia': ['Windhoek','Walvis Bay','Swakopmund','Oshakati','Rundu','Katima Mulilo','Keetmanshoop','Otjiwarongo'],
'Nauru': ['Yaren','Anabar','Anetan','Aiwo','Nibok','Baiti'],
'Nepal': ['Kathmandu','Pokhara','Lalitpur','Bharatpur','Biratnagar','Birgunj','Dharan','Butwal','Hetauda'],
'Netherlands': ['Amsterdam','Rotterdam','The Hague','Utrecht','Eindhoven','Tilburg','Groningen','Almere','Breda','Nijmegen'],
'New Zealand': ['Auckland','Wellington','Christchurch','Hamilton','Tauranga','Dunedin','Palmerston North','Napier','Hastings'],
'Nicaragua': ['Managua','León','Masaya','Matagalpa','Chinandega','Estelí','Granada','Jinotega'],
'Niger': ['Niamey','Zinder','Maradi','Agadez','Tahoua','Dosso','Diffa'],
'Nigeria': ['Lagos','Abuja','Ibadan','Benin City','Port Harcourt','Aba','Onitsha','Owerri','Enugu','Uyo','Calabar'],
'North Korea': ['Pyongyang','Hamhung','Chongjin','Nampo','Sinuiju','Wonsan','Hyesan'],
'North Macedonia': ['Skopje','Bitola','Kumanovo','Prilep','Tetovo','Ohrid','Veles'],
'Norway': ['Oslo','Bergen','Stavanger','Trondheim','Drammen','Fredrikstad','Kristiansand','Sandnes','Tromsø'],
'Oman': ['Muscat','Salalah','Sohar','Nizwa','Sur','Ibri','Buraimi'],
'Pakistan': ['Karachi','Lahore','Islamabad','Rawalpindi','Faisalabad','Multan','Peshawar','Quetta','Gujranwala','Sialkot','Bahawalpur'],
'Palau': ['Ngerulmud','Koror','Melekeok','Ngaraard','Airai'],
'Panama': ['Panama City','San Miguelito','Colón','David','Santiago','Chitré','La Chorrera'],
'Papua New Guinea': ['Port Moresby','Lae','Mount Hagen','Madang','Goroka','Kokopo','Arawa'],
'Paraguay': ['Asunción','Ciudad del Este','San Lorenzo','Luque','Capiatá','Lambaré','Fernando de la Mora'],
'Peru': ['Lima','Arequipa','Trujillo','Chiclayo','Piura','Cusco','Iquitos','Huancayo','Ayacucho','Tacna'],
'Philippines': ['Manila','Quezon City','Cebu City','Davao City','Makati','Taguig','Pasig','Pasay','Iloilo City','Bacolod'],
'Poland': ['Warsaw','Kraków','Łódź','Wrocław','Poznań','Gdańsk','Szczecin','Bydgoszcz','Lublin','Katowice'],
'Portugal': ['Lisbon','Porto','Vila Nova de Gaia','Braga','Coimbra','Aveiro','Faro','Setúbal','Leiria'],
'Qatar': ['Doha','Al Rayyan','Al Wakrah','Umm Salal','Al Khor','Dukhan','Mesaieed'],
'Romania': ['Bucharest','Cluj-Napoca','Timișoara','Iași','Constanța','Craiova','Brașov','Galați','Ploiești','Oradea','Arad'],
'Russia': ['Moscow','Saint Petersburg','Novosibirsk','Yekaterinburg','Kazan','Nizhny Novgorod','Chelyabinsk','Samara','Omsk','Rostov-on-Don','Ufa','Krasnoyarsk'],
'Rwanda': ['Kigali','Butare','Gitarama','Ruhengeri','Gisenyi','Byumba','Cyangugu'],
'Saint Kitts and Nevis': ['Basseterre','Charlestown','Sandy Point','Dieppe Bay Town','Cayon'],
'Saint Lucia': ['Castries','Vieux Fort','Micoud','Dennery','Gros Islet','Soufrière'],
'Saint Vincent': ['Kingstown','Georgetown','Barrouallie','Chateaubelair','Port Elizabeth'],
'Samoa': ['Apia','Vaitele','Faleasiu','Siusega','Leulumoega'],
'San Marino': ['San Marino','Serravalle','Borgo Maggiore','Domagnano','Fiorentino','Faetano','Acquaviva'],
'Sao Tome': ['São Tomé','Trindade','Neves','Guadalupe','Santana'],
'Saudi Arabia': ['Riyadh','Jeddah','Mecca','Medina','Dammam','Khobar','Dhahran','Taif','Tabuk','Buraidah','Abha','Jizan'],
'Senegal': ['Dakar','Touba','Thiès','Saint-Louis','Ziguinchor','Kaolack','Mbour'],
'Serbia': ['Belgrade','Novi Sad','Niš','Kragujevac','Subotica','Zrenjanin','Pančevo','Čačak','Kraljevo'],
'Seychelles': ['Victoria','Anse Boileau','Anse Royale','Beau Vallon','Takamaka'],
'Sierra Leone': ['Freetown','Bo','Kenema','Makeni','Koidu'],
'Singapore': ['Singapore'],
'Slovakia': ['Bratislava','Košice','Prešov','Žilina','Nitra','Banská Bystrica','Trnava','Trenčín'],
'Slovenia': ['Ljubljana','Maribor','Celje','Kranj','Velenje','Koper','Novo Mesto'],
'Solomon Islands': ['Honiara','Gizo','Auki','Munda','Tulagi'],
'Somalia': ['Mogadishu','Hargeisa','Bosaso','Kismayo','Baidoa','Beledweyne'],
'South Africa': ['Johannesburg','Cape Town','Durban','Pretoria','Gqeberha','Bloemfontein','East London','Polokwane','Nelspruit'],
'South Korea': ['Seoul','Busan','Incheon','Daegu','Daejeon','Gwangju','Ulsan','Suwon','Changwon','Goyang'],
'South Sudan': ['Juba','Wau','Malakal','Yei','Aweil'],
'Spain': ['Madrid','Barcelona','Valencia','Seville','Zaragoza','Málaga','Murcia','Palma','Las Palmas','Bilbao','Alicante','Córdoba'],
'Sri Lanka': ['Colombo','Dehiwala-Mount Lavinia','Moratuwa','Negombo','Kandy','Galle','Jaffna','Batticaloa'],
'Sudan': ['Khartoum','Omdurman','Port Sudan','El Obeid','Kassala','Wad Madani','Nyala'],
'Suriname': ['Paramaribo','Lelydorp','Nieuw Nickerie','Moengo','Albina'],
'Sweden': ['Stockholm','Gothenburg','Malmö','Uppsala','Västerås','Örebro','Linköping','Helsingborg','Jönköping'],
'Switzerland': ['Zurich','Geneva','Basel','Lausanne','Bern','Winterthur','Lucerne','St. Gallen','Lugano'],
'Syria': ['Damascus','Aleppo','Homs','Hama','Latakia','Tartus','Deir ez-Zor','Raqqa'],
'Taiwan': ['Taipei','New Taipei','Taichung','Tainan','Kaohsiung','Hsinchu','Taoyuan','Keelung','Chiayi'],
'Tajikistan': ['Dushanbe','Khujand','Bokhtar','Kulob','Istaravshan','Panjakent','Tursunzoda'],
'Tanzania': ['Dar es Salaam','Dodoma','Arusha','Mwanza','Zanzibar City','Mbeya','Morogoro','Tanga'],
'Thailand': ['Bangkok','Chiang Mai','Phuket','Pattaya','Hat Yai','Khon Kaen','Udon Thani','Nakhon Ratchasima','Surat Thani','Krabi','Hua Hin','Rayong','Chiang Rai'],
'Timor-Leste': ['Dili','Baucau','Maliana','Suai','Liquiça','Aileu'],
'Togo': ['Lomé','Sokodé','Kara','Atakpamé','Dapaong','Tsévié'],
'Tonga': ['Nukuʻalofa','Neiafu','Haveluloto','Vaini','Pangai'],
'Trinidad and Tobago': ['Port of Spain','San Fernando','Chaguanas','Arima','Point Fortin','Scarborough'],
'Tunisia': ['Tunis','Sfax','Sousse','Ettadhamen','Kairouan','Gabès','Bizerte','Nabeul'],
'Turkey': ['Istanbul','Ankara','Izmir','Bursa','Antalya','Adana','Konya','Gaziantep','Kayseri','Eskisehir'],
'Turkmenistan': ['Ashgabat','Turkmenabat','Dashoguz','Mary','Balkanabat','Bayramaly'],
'Tuvalu': ['Funafuti','Vaiaku','Fongafale'],
'Uganda': ['Kampala','Gulu','Lira','Mbarara','Jinja','Mbale','Arua','Entebbe'],
'Ukraine': ['Kyiv','Kharkiv','Odesa','Dnipro','Lviv','Zaporizhzhia','Mykolaiv','Vinnytsia','Chernihiv'],
'United Arab Emirates': ['Dubai','Abu Dhabi','Sharjah','Al Ain','Ajman','Ras Al Khaimah','Fujairah','Umm Al Quwain'],
'United Kingdom': ['London','Birmingham','Manchester','Leeds','Liverpool','Sheffield','Bristol','Nottingham','Leicester','Coventry'],
'United States': ['New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia','San Antonio','San Diego','Dallas','San Jose','Austin','Seattle','San Francisco'],
'Uruguay': ['Montevideo','Salto','Paysandú','Las Piedras','Rivera','Maldonado'],
'Uzbekistan': ['Tashkent','Samarkand','Bukhara','Namangan','Andijan','Fergana','Nukus'],
'Vanuatu': ['Port Vila','Luganville','Norsup','Isangel'],
'Vatican City': ['Vatican City'],
'Venezuela': ['Caracas','Maracaibo','Valencia','Barquisimeto','Maracay','Ciudad Guayana','Maturín','Barcelona'],
'Vietnam': ['Ho Chi Minh City','Hanoi','Da Nang','Hai Phong','Can Tho','Bien Hoa','Nha Trang','Hue','Vung Tau'],
'Yemen': ['Sanaa','Aden','Taiz','Al Hudaydah','Ibb','Mukalla'],
'Zambia': ['Lusaka','Ndola','Kitwe','Chingola','Mufulira','Livingstone','Kabwe'],
'Zimbabwe': ['Harare','Bulawayo','Chitungwiza','Mutare','Gweru','Kwekwe','Masvingo']
};